### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by lenghaha** [m3u8playlist/dp#5]
你好 app链接打不开 请问安装电视有可使用的软件吗

**Comment by m3u8playlist** [comment]
app在tg资源群里,下载ipa自签,只支持iOS,不支持tvOS

**Comment by m3u8playlist** [comment]
app在tg资源群里,下载ipa自签,只支持iOS,不支持tvOS

**Comment by cckenaaa** [comment]
tg资源群是没了吗？

**Comment by m3u8playlist** [comment]
> tg资源群是没了吗？

https://t.me/+Uo2xZNAl5lvKx98t
https://t.me/+S-LcawVLuVTJte2Q
