### ISSUE TITLE
大佬还在吗？

### ISSUE THREAD

**Issue by zyx092213** [m3u8playlist/dp#6]
大佬有时间方便的话可以做个missav的采集链接吗？感谢！

**Comment by m3u8playlist** [comment]
加不了,missav和avgle一样,防盗功能太强

**Comment by m3u8playlist** [comment]
提供一下名字,我看看是不是被bot封了

**Comment by zyx092213** [comment]
> 提供一个名字，我看看是不是被机器人封了

beiwoqpvn  没进过这个群

**Comment by m3u8playlist** [comment]
> > 提供一个名字，我看看是不是被机器人封了
> 
> 
> 
> beiwoqpvn  没进过这个群 

再加群试试

**Comment by lhzbxx** [comment]
> > > 提供一个名字，我看看是不是被机器人封了
> > 
> > 
> > beiwoqpvn  没进过这个群
> 
> 再加群试试

大佬，刚才加电报群没注意机器人验证，点的时候超时被封了，求解封一下：lhzbxx

**Comment by m3u8playlist** [comment]
已解禁，再试试
2024年2月15日 +0800 PM12:52 LH ***@***.***>，写道：
